version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "6543:6543"
    volumes:
      - .:/app
    networks:
      - api_network
networks:
  api_network:
    driver: bridge
